/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './front/**/*.{tsx,jsx}', './*.{tsx,jsx}', './layout/**/*.{tsx,jsx}', './messaging/**/*.{tsx,jsx}', './store/**/*.ts'],
  theme: {
    extend: {
      fontFamily: {
        sans: ['Inter', 'system-ui', '-apple-system', 'sans-serif'],
        mono: ['"JetBrains Mono"', '"Fira Mono"', 'monospace'],
      },
      colors: {
        /* MD3 semantic */
        primary: 'var(--md-sys-color-primary)',
        'on-primary': 'var(--md-sys-color-on-primary)',
        'primary-container': 'var(--md-sys-color-primary-container)',
        'on-primary-container': 'var(--md-sys-color-on-primary-container)',
        secondary: 'var(--md-sys-color-secondary)',
        'on-secondary': 'var(--md-sys-color-on-secondary)',
        'secondary-container': 'var(--md-sys-color-secondary-container)',
        'on-secondary-container': 'var(--md-sys-color-on-secondary-container)',
        tertiary: 'var(--md-sys-color-tertiary)',
        'on-tertiary': 'var(--md-sys-color-on-tertiary)',
        'tertiary-container': 'var(--md-sys-color-tertiary-container)',
        'on-tertiary-container': 'var(--md-sys-color-on-tertiary-container)',
        error: 'var(--md-sys-color-error)',
        'on-error': 'var(--md-sys-color-on-error)',
        'error-container': 'var(--md-sys-color-error-container)',
        'on-error-container': 'var(--md-sys-color-on-error-container)',
        surface: 'var(--md-sys-color-surface)',
        'on-surface': 'var(--md-sys-color-on-surface)',
        'surface-variant': 'var(--md-sys-color-surface-variant)',
        'on-surface-variant': 'var(--md-sys-color-on-surface-variant)',
        outline: 'var(--md-sys-color-outline)',
        'outline-variant': 'var(--md-sys-color-outline-variant)',
        background: 'var(--md-sys-color-background)',
        'on-background': 'var(--md-sys-color-on-background)',
        scrim: 'var(--md-sys-color-scrim)',
        'surf-dim': 'var(--md-sys-color-surface-dim)',
        'surf-bright': 'var(--md-sys-color-surface-bright)',
        'surf-low': 'var(--md-sys-color-surface-container-lowest)',
        'surf-cl': 'var(--md-sys-color-surface-container-low)',
        'surf-c': 'var(--md-sys-color-surface-container)',
        'surf-ch': 'var(--md-sys-color-surface-container-high)',
        'surf-chh': 'var(--md-sys-color-surface-container-highest)',
        /* Status */
        online: 'var(--color-status-online)',
        idle: 'var(--color-status-idle)',
        busy: 'var(--color-status-busy)',
        focus: 'var(--color-status-focus)',
        invisible: 'var(--color-status-invisible)',
      },
      borderRadius: {
        'md3-xs': 'var(--borderRadius-xs)',
        'md3-sm': 'var(--borderRadius-sm)',
        'md3-md': 'var(--borderRadius-md)',
        'md3-lg': 'var(--borderRadius-lg)',
        'md3-li': 'var(--borderRadius-li)',
        'md3-xl': 'var(--borderRadius-xl)',
        'md3-xli': 'var(--borderRadius-xli)',
        'md3-xxl': 'var(--borderRadius-xxl)',
        'md3-full': 'var(--borderRadius-full)',
      },
      boxShadow: {
        md3: '0 1px 3px rgba(0,0,0,0.3), 0 4px 8px rgba(0,0,0,0.2)',
        'md3-toolbar': '0 0 3px var(--md-sys-color-shadow)',
        'md3-primary': '0 0 20px color-mix(in srgb, var(--md-sys-color-primary) 35%, transparent)',
        scrim: '0 0 0 100vmax rgba(0,0,0,0.55)',
      },
      keyframes: {
        scrimFadeIn: {
          from: { opacity: '0' },
          to: { opacity: '1' },
        },
        modalSlideIn: {
          from: { opacity: '0', transform: 'scale(0.92) translateY(12px)' },
          to: { opacity: '1', transform: 'scale(1) translateY(0)' },
        },
        slideUp: {
          from: { opacity: '0', transform: 'translateY(8px)' },
          to: { opacity: '1', transform: 'translateY(0)' },
        },
        fadeIn: {
          from: { opacity: '0' },
          to: { opacity: '1' },
        },
      },
      animation: {
        'scrim-in': 'scrimFadeIn 0.2s ease-out both',
        'modal-in': 'modalSlideIn 0.25s cubic-bezier(0.2,0.8,0.2,1) both',
        'slide-up': 'slideUp 0.2s ease both',
        'fade-in': 'fadeIn 0.15s ease both',
      },
      transitionTimingFunction: {
        md3: 'cubic-bezier(0.2, 0.8, 0.2, 1)',
      },
    },
  },
  plugins: [],
};
